### ISSUE TITLE
Getting invalid byte sequence in Bundler when added this to a Gem

### ISSUE THREAD

**Issue by confact** [Manfred/Ensure-encoding#5]
I added this to one of my gem to handle encoding better, i added it and just changed one line and added require and bundler became crazy when i added my gem (that has dependency to yours) to my app.

```
bundle stderr: /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/ui/shell.rb:92:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/ui/shell.rb:92:in `strip_leading_spaces'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/ui/shell.rb:97:in `word_wrap'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/ui/shell.rb:83:in `tell_me'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/ui/shell.rb:29:in `error'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:9:in `rescue in with_friendly_errors'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    from /home/deploy/.rvm/gems/ruby-2.1.4/gems/bundler-1.9.6/bin/bundle:18:in `<top (required)>'
    from /home/deploy/.rvm/gems/ruby-2.1.4/bin/bundle:23:in `load'
    from /home/deploy/.rvm/gems/ruby-2.1.4/bin/bundle:23:in `<main>'
    from /home/deploy/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
    from /home/deploy/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

I use Ruby 2.1.4 and bundle 1.9.6

What is the problem?

**Comment by Manfred** [comment]
The problem seems to be that Ruby has implemented its own `force_encoding` on string starting 2.1.0 and it's not fully compatible with mine.

http://ruby-doc.org/core-2.1.0/String.html#method-i-force_encoding

In what way are you using Ensure-encoding? Maybe you can switch to Ruby vanilla methods?
